### PR TITLE
Bug fixes and a few additions

### PR DESCRIPTION
**Pull request by nazrhyn**
Hello. We found your library and started using it, and then ran into a few issues that I've addressed in this pull request.

## Changes
* Renamed AmericanExpress..js to AmericanExpress.test.js
* Added .editorconfig file with what looked like the right settings
* Fixed the spelling of Diners Club (used to be Dinners Club)
* Added Discover to the cards list (it used to be missing)
* Fixed description text in package.json and bower.json
* Fixed typo where JCB was JBC in CreditCard name and test describe
* Removed spaces from JCB CardNumber properties of jcb.numbers.json
* Fixed some spelling and other errors in README

## Possible Issues
I wasn't able to get 100% passing tests even with the current state of master. This test kept failing:
```
$ npm run test

> credit-card-validate@0.9.2 test C:\code\opensource\credit-card-validate
> node node_modules/karma/bin/karma start karma.conf.js

28 03 2017 18:10:55.597:WARN [karma]: Port 9876 in use
28 03 2017 18:10:55.601:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9877/
28 03 2017 18:10:55.602:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
28 03 2017 18:10:55.610:INFO [launcher]: Starting browser PhantomJS
28 03 2017 18:10:58.580:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket EWuqKA6nZOYZu75tAAAA with id 11774188
PhantomJS 2.1.1 (Windows 7 0.0.0) Test base credit card should resolve future date as non expired FAILED
        Expected true to equal false.
        http://localhost:9877test/CreditCard/CreditCard.test.js:33:87
        loaded@http://localhost:9877/context.js:151:17
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 32 of 32 (1 FAILED) (0.099 secs / 0.097 secs)
```

I had to modify your JCB numbers file as with the spaces in the numbers (e.g. `"1234 1234 1234 1234"`), they would not pass number validation. They failed in the Luhn validation check. I noticed that all other number definition files did not have those spaces. I'm not sure what the difference between master and after my changes was that would cause that to start failing.

## Comments
I ran the `build` script and generated new `dist/` files, but they ended up with slightly different indentation. Not sure why, but you'll see it in the diff.
<hr>
Let me know if you have any questions or if I did something wrong!

### CODE REVIEW

**Comment by nazrhyn** [comment]
Looks like all the tests ran successfully in Travis, though. Not sure what the issue was with my environment.

**Comment by fabulator** [comment]
Great, thanks! Tests passed on my local.

**Comment by nazrhyn** [comment]
Thanks for the fast merge. I was going to make one additional change but you were too quick!

Locally I have the `core.autocrlf` git config setting set to `false` so it always checks out line endings as they are with no modification. However, I think that has an unexpected interaction with `text=auto` in your [.gitattributes](https://github.com/fabulator/credit-card-validate/blob/master/.gitattributes#L2) file: the files were getting changed to CRLF (as I'm on Windows).

Not understanding that interaction led me to assume you had committed them that way, which led me to add these lines in the [.editorconfig](https://github.com/fabulator/credit-card-validate/blob/master/.editorconfig#L4) file that I added:

```
[*]
end_of_line = crlf
```

In reality, you probably don't want that, so you might want to just drop those two lines. The other two lines about tabs and tab width are still good.

Thanks again! Any idea when you'll publish 0.9.3 to bower/npm?

**Comment by fabulator** [comment]
I published new version of npm package. 
And I added tag version to git, so it should be pushed to bower - I can see that bower image in desc was update.

If you are facing some issue with update, let me know.

**Comment by nazrhyn** [comment]
It's up on NPM and Bower. Thanks!

**Pull request merged**
